In [ ]:
# Импортируем объект Counter из модуля collections
from collections import Counter
# Создаём пустой объект Counter
cars_moscow = ['black', 'black', 'white', 'black', 'black', 'white', 'yellow', 'yellow', 'yellow']
cars_spb = ['red', 'black', 'black', 'white', 'white', 'yellow', 'yellow', 'red', 'white']

counter_moscow = Counter(cars_moscow)
counter_spb = Counter(cars_spb)
 
print(counter_moscow)
print(counter_spb)
print(counter_moscow + counter_spb)
# counter_moscow.subtract(counter_spb)
# print(counter_moscow)
# print(counter_moscow - counter_spb)
print(*counter_moscow.elements())
print(list(counter_moscow)) # список уникальных элементов
print(dict(counter_moscow)) # можно превратить Counter в обычный словарь
print(counter_moscow.most_common()) # Функция most_common() позволяет получить список из кортежей элементов в порядке убывания их встречаемости
print(counter_moscow.most_common(2)) # задаёт желаемое число первых наиболее частых элементов, например, 2
counter_moscow.clear() # функция clear() позволяет полностью обнулить счётчик
print(counter_moscow)

In [9]:
from collections import defaultdict
# Создадим defaultdict, в котором при обращении по несуществующему ключу будет автоматически создаваться новый список
groups = defaultdict(list)

students = [('Ivanov',1),('Smirnov',4),('Petrov',3),('Kuznetsova',1),
            ('Nikitina',2),('Markov',3),('Pavlov',2)]

for student, group in students:
    groups[group].append(student)
 
print(groups)
print(groups[3])
print(groups[2021]) # Теперь в словаре groups автоматически появился элемент 2021 с пустым списком внутри, несмотря на то что мы его не создавали:
print(groups)

dict_object = dict()
defaultdict_object = defaultdict()
 
print(type(dict_object)) #  каким именно словарём мы имеем дело в коде, можно с помощью встроенной функции type
# <class 'dict'>
print(type(defaultdict_object))
# <class 'collections.defaultdict'>

print(dict_object)
# {}
print(defaultdict_object)
# defaultdict(None, {})

defaultdict(<class 'list'>, {1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov']})
['Petrov', 'Markov']
[]
defaultdict(<class 'list'>, {1: ['Ivanov', 'Kuznetsova'], 4: ['Smirnov'], 3: ['Petrov', 'Markov'], 2: ['Nikitina', 'Pavlov'], 2021: []})
<class 'dict'>
<class 'collections.defaultdict'>
{}
defaultdict(None, {})


In [ ]:
from collections import OrderedDict
data = [('Ivan', 19),('Mark', 25),('Andrey', 23),('Maria', 20)]
# Специальный словарь, который гарантирует сохранение ключей в порядке их добавления, называется OrderedDict:
ordered_client_ages = OrderedDict(data)
print(ordered_client_ages)
# По результатам 3 повторов получились вот такие результаты:
# OrderedDict([('Ivan', 19), ('Mark', 25), ('Andrey', 23), ('Maria', 20)])
# OrderedDict([('Ivan', 19), ('Mark', 25), ('Andrey', 23), ('Maria', 20)])
# OrderedDict([('Ivan', 19), ('Mark', 25), ('Andrey', 23), ('Maria', 20)])

data = [('Ivan', 19),('Mark', 25),('Andrey', 23),('Maria', 20)]
# Сортируем по второму значению из кортежа, то есть по возрасту
ordered_client_ages = OrderedDict(sorted(data, key=lambda x: x[1]))
print(ordered_client_ages)
# OrderedDict([('Ivan', 19), ('Maria', 20), ('Andrey', 23), ('Mark', 25)])

# Если теперь добавить нового человека в словарь, новая запись окажется в конце:
ordered_client_ages['Nikita'] = 18
print(ordered_client_ages)
# OrderedDict([('Ivan', 19), ('Maria', 20), ('Andrey', 23), ('Mark', 25), ('Nikita', 18)])

# Если удалить элемент, а затем добавить его снова, он также окажется в конце:
del ordered_client_ages['Andrey']
print(ordered_client_ages)
# OrderedDict([('Ivan', 19), ('Mark', 25), ('Maria', 20), ('Nikita', 18)])
ordered_client_ages['Andrey'] = 23
print(ordered_client_ages)
# OrderedDict([('Ivan', 19), ('Mark', 25), ('Maria', 20), ('Nikita', 18), ('Andrey', 23)])

In [ ]:
from collections import deque
dq = deque()
print(dq)
# deque([])

clients = deque()
clients.append('Ivanov')
clients.append('Petrov')
clients.append('Smirnov')
clients.append('Tikhonova')
print(clients)
# deque(['Ivanov', 'Petrov', 'Smirnov', 'Tikhonova'])

print(clients[2])
# Smirnov

first_client = clients.popleft()
second_client = clients.popleft()

# Освободилось два оператора — заберём двоих человек из начала очереди с помощью popleft: 
print("First client:", first_client)
print("Second client:", second_client)
print(clients)
# First client: Ivanov
# Second client: Petrov
# deque(['Smirnov', 'Tikhonova'])

# Вдруг появился VIP-клиент. Для него тоже нет свободного оператора, но добавить его нужно в начало очереди с помощью appendleft:
clients.appendleft('Vip-client')
print(clients)
# deque(['Vip-client', 'Smirnov', 'Tikhonova'])

tired_client = clients.pop() # Последний клиент в очереди устал ждать и отменил вызов. Удалим его с помощью pop:
print(tired_client, "left the queue")
print(clients)
# Tikhonova left the queue
# deque(['Vip-client', 'Smirnov'])

# чтобы удалить конкретный элемент по индексу, необходимо воспользоваться встроенной конструкцией del:
clients = deque(['Ivanov', 'Petrov', 'Smirnov', 'Tikhonova'])
print(clients)
# deque(['Ivanov', 'Petrov', 'Smirnov', 'Tikhonova'])
del clients[2]
print(clients)
# deque(['Ivanov', 'Petrov', 'Tikhonova'])

# В скобках передаём список при создании deque,
# чтобы сразу добавить все его элементы в очередь
shop = deque([1, 2, 3, 4, 5])
print(shop)
# deque([1, 2, 3, 4, 5])
shop.extend([11, 12, 13, 14, 15, 16, 17])
print(shop)
# deque([1, 2, 3, 4, 5, 11, 12, 13, 14, 15, 16, 17])

# При создании очереди можно также указать её максимальную длину с помощью параметра maxlen. Сделать это можно как при создании
# пустой очереди, так и при создании очереди от заданного итерируемого объекта:
limited = deque(maxlen=3)
print(limited)
# deque([], maxlen=3)
 
limited_from_list = deque([1,3,4,5,6,7], maxlen=3)
print(limited_from_list)
# deque([5, 6, 7], maxlen=3)

# в очереди с ограниченной длиной сохраняются только последние элементы, а первые исчезают из памяти:
limited.extend([1,2,3])
print(limited)
# deque([1, 2, 3], maxlen=3)
 
print(limited.append(8))
# None
print(limited)
# deque([2, 3, 8], maxlen=3)

In [ ]:
temps = [20.6, 19.4, 19.0, 19.0, 22.1,
        22.5, 22.8, 24.1, 25.6, 27.0,
        27.0, 25.6, 26.8, 27.3, 22.5,
        25.4, 24.4, 23.7, 23.6, 22.6,
        20.4, 17.9, 17.3, 17.3, 18.1,
        20.1, 22.2, 19.8, 21.3, 21.3,
        21.9]

days = deque(maxlen=7)
 
for temp in temps:
    # Добавляем температуру в очередь
    days.append(temp)
    # Если длина очереди оказалась равной максимальной длине очереди (7),
    # печатаем среднюю температуру за последние 7 дней
    if len(days) == days.maxlen:
        print(round(sum(days) / len(days), 2), end='; ')
# Напечатаем пустую строку, чтобы завершить действие параметра
# end. Иначе следующая строка окажется напечатанной на предыдущей
print("")
# Результат:
# 20.77; 21.27; 22.16; 23.3; 24.44; 24.94; 25.56; 26.2; 25.97;
# 25.94; 25.57; 25.1; 24.81; 24.21; 23.23; 22.57; 21.41; 20.4;
# 19.6; 19.1; 19.04; 18.96; 19.44; 20.01; 20.67;

In [ ]:
dq = deque([1,2,3,4,5])
dq.reverse() # reverse позволяет поменять порядок элементов в очереди на обратный:
dq.rotate(2) # rotate переносит n заданных элементов из конца очереди в начало:
dq.rotate(-2) # Отрицательное значение аргумента переносит # n элементов из начала в конец

dq = [1,2,4,2,3,1,5,4,4,4,4,4,3]
print(dq.index(4))
# 2
print(dq.count(4))

dq.clear() # Наконец, функция clear позволяет очистить очередь:

In [ ]:
temps = [('2000', -4.4), ('2001', -2.5), ('2002', -4.4), ('2003', -9.5)]
def check(temps):
    ordered_temps = OrderedDict(sorted(temps, key=lambda x: -x[1]))
    return ordered_temps

check(temps)
# OrderedDict([('2001', -2.5), ('2000', -4.4), ('2002', -4.4), ('2003', -9.5)])

In [ ]:
from collections import deque
def brackets(line):
    bracket_deq = deque()
    try:
        for elem in line:
            if elem == "(": bracket_deq.append(elem)
            if elem == ")": bracket_deq.pop()
    except IndexError:
        return False
    if len(bracket_deq) == 0:
        return True
    else:
        return False

print(brackets("(()())"))
# True
print(brackets(""))
# True
print(brackets("(()()))"))
# False

In [ ]:
ratings = [('Old York', 3.3), ('New Age', 4.6), ('Old Gold', 3.3), ('General Foods', 4.8),
           ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1),
           ('WokToWork', 4.9), ('WokAndRice', 4.9), ('Old Wine Cellar', 3.3), ('Nice Cakes', 3.9)]

#Необходимо отсортировать кортеж по убыванию рейтинга. Если рейтинги совпадают, то отсортировать кафе дополнительно по названию 
# в алфавитном порядке.
#Получите словарь cafes с упорядоченными ключами из отсортированного списка, где ключи — названия кафе, а значения — их рейтинг.
from collections import OrderedDict
ratings.sort(key=lambda x: (-x[1], x[0])) # Сортировать по 2 элементу (наоборот), а затем по 1 элементу
cafes = OrderedDict(ratings)
print(cafes)
# OrderedDict([('WokAndRice', 4.9), ('WokToWork', 4.9), ('General Foods', 4.8), ('New Age', 4.6), ('Belissimo', 4.5), ('CakeAndCoffee', 4.2), ('CakeOClock', 4.2), ('CakeTime', 4.1), ('Nice Cakes', 3.9), ('Old Gold', 3.3), ('Old Wine Cellar', 3.3), ('Old York', 3.3)])

In [41]:
from collections import defaultdict
from collections import deque

tasks = [(36871, 'office', False),
(40690, 'office', False),
(35364, 'voltage', False),
(41667, 'voltage', True),
(33850, 'office', False)]

from collections import defaultdict, deque

def task_manager(tasks):
    servers = defaultdict(deque)
    for task in tasks:
        if task[-1]:
            servers[task[1]].appendleft(task[0])
        else:
            servers[task[1]].append(task[0])
    return servers

 
print(task_manager(tasks))
# defaultdict(, {'voltage': deque([41667, 35364]),
# 'office': deque([36871, 40690, 33850])})

defaultdict(<class 'collections.deque'>, {'office': deque([36871, 40690, 33850]), 'voltage': deque([41667, 35364])})


In [ ]:
import numpy as np
a = np.int64(25)
print(a)
# Можно применить к самому
# названию типа данных
np.iinfo(np.int64)
# iinfo(min=-128, max=127, dtype=int8)

# Можно применить к существующему
# конкретному объекту
np.iinfo(a)
# iinfo(min=-128, max=127, dtype=int8)

In [91]:
b = np.uint64(124)
print(b)
# 124
print(type(b))
# <class 'numpy.uint8'>
np.iinfo(b)
# iinfo(min=0, max=255, dtype=uint8)
b = np.int16(124)
np.iinfo(b)

124
<class 'numpy.uint64'>


iinfo(min=-32768, max=32767, dtype=int16)

In [ ]:
b = np.uint8(-456)
print(b)
# 124
print(type(b))
# <class 'numpy.uint8'>
np.iinfo(b)
# iinfo(min=0, max=255, dtype=uint8)

In [ ]:
np.finfo(np.float16)
# finfo(resolution=0.001, min=-6.55040e+04, max=6.55040e+04, dtype=float16)
np.finfo(np.float32)
# finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32)
np.finfo(np.float64)
# finfo(resolution=1e-15, min=-1.7976931348623157e+308, max=1.7976931348623157e+308, dtype=float64)
# np.finfo(np.float128)
# finfo(resolution=1e-18, min=-1.189731495357231765e+4932, max=1.189731495357231765e+4932, dtype=float128)
print(np.sctypeDict)
print(len(np.sctypeDict))
# 158, но может быть 135 или 139
print(*sorted(map(str, set(np.sctypeDict.values()))), sep='\n')

In [ ]:
import numpy as np
arr = np.array([1,5,2,9,10])
arr
# array([ 1,  5,  2,  9, 10])

# Перечислить список из списков можно
# было и в одну строку, но на нескольких
# строках получается нагляднее
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ])
nd_arr

In [78]:
arr = np.array([1,5,2,9,10])
arr.dtype

arr = np.array([1,5,2,9,10], dtype=np.int8)
arr

arr = np.float64(arr)
arr

array([ 1.,  5.,  2.,  9., 10.])

In [63]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

arr.ndim # Узнать размерность массива можно с помощью .ndim:
# 1
nd_arr.ndim
# 2

arr.size # Узнать общее число элементов в массиве можно с помощью .size:
# 5
nd_arr.size
# 9

arr.shape # Форма или структура массива хранится в атрибуте .shape:
# (5,)
nd_arr.shape
# (3, 3)

(3, 3)

In [211]:
zeros_1d = np.zeros(5) # Создадим одномерный массив из пяти элементов
zeros_1d
# array([0., 0., 0., 0., 0.])

zeros_3d = np.zeros((5,4,3), dtype=np.float32) # Создадим трёхмерный массив с формой 5x4x3 и типом float32:
print(zeros_3d.shape)
# (5, 4, 3)

(5, 4, 3)


In [ ]:
# Вот её сигнатура: arange([start,] stop, [step,], dtype=None)
# Аргументы start (по умолчанию 0), step (по умолчанию 1) и dtype (определяется автоматически) являются необязательными:
np.arange(5)
# array([0, 1, 2, 3, 4])
np.arange(2.5, 5)
# array([2.5, 3.5, 4.5])
np.arange(2.5, 5, 0.5)
# array([2.5, 3. , 3.5, 4. , 4.5])
np.arange(2.5, 5, 0.5, dtype=np.float16)
# array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

In [ ]:
# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

#start и stop являются обязательными параметрами, задающими начало и конец возвращаемого диапазона;
#num — параметр, задающий число элементов, которое должно оказаться в массиве (по умолчанию 50);
#endpoint — включён или исключён конец диапазона (по умолчанию включён);
#retstep (по умолчанию False) позволяет указать, возвращать ли использованный шаг между значениями, помимо самого массива;
#dtype — уже хорошо знакомый нам параметр, задающий тип данных (если не задан, определяется автоматически).

arr = np.linspace(1, 2, 10)
arr
# array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
#        1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

arr = np.linspace(1, 2, 10, endpoint=False)
arr
# array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

arr, step = np.linspace(1, 2, 10, endpoint=True, retstep=True)
#print(step)
# 0.1111111111111111

arr, step = np.linspace(1, 2, 10, endpoint=False, retstep=True)
#print(step)
# 0.1

arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
print(round(step,2))

In [ ]:
import numpy as np
arr = np.arange(8)
arr
# array([0, 1, 2, 3, 4, 5, 6, 7])
arr.shape = (2, 4) # Поменять форму массива arr можно с помощью присвоения атрибуту shape кортежа с желаемой формой:
arr
# array([[0, 1, 2, 3],
#        [4, 5, 6, 7]])
# Чтобы оставить исходный массив без изменений и дополнительно получить новый массив новой формы, нужно использовать функцию reshape
arr = np.arange(8)
arr_new = arr.reshape((2, 4))
arr_new
# array([[0, 1, 2, 3],
#       [4, 5, 6, 7]])
arr = np.arange(8)
arr_new = arr.reshape((2, 4), order='F') # У функции reshape есть дополнительный именованный аргумент order.
# Он задаёт принцип, по которому элементы заполняют массив новой формы.
# Если order='C' (по умолчанию), массив заполняется по строкам, как в примере выше. Если order='F', массив заполняется числами по столбцам:
arr_new
# array([[0, 2, 4, 6],
#       [1, 3, 5, 7]])
arr_trans = arr.transpose() # операция меняет строки и столбцы массива местами

In [ ]:
# ИНДЕКСЫ И СРЕЗЫ В МАССИВАХ
arr = np.linspace(1, 2, 6)
# array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])
print(arr[2:4])
# [1.4 1.6]
print(arr[::-1])
# [2.  1.8 1.6 1.4 1.2 1. ]
nd_array =  np.linspace(0, 6, 12, endpoint=False).reshape(3,4) # Создадим двумерный массив из одномерного
nd_array
# array([[0. , 0.5, 1. , 1.5],
#        [2. , 2.5, 3. , 3.5],
#        [4. , 4.5, 5. , 5.5]])
nd_array[1, 2]
# 3.0
nd_array[:2, 2] # получим все элементы из колонки 3 для первых двух строк
# array([1., 3.])
nd_array[1:, 2:4] # Можно применять срезы сразу и к строкам, и к столбцам
# array([[3. , 3.5],
#       [5. , 5.5]])
nd_array[:, 2:4] # Чтобы получить все значения из какой-то оси, можно оставить на её месте двоеточие.
# Например, из всех строк получим срез с третьего по четвёртый столбцы:
nd_array[:2]
# array([[0. , 0.5, 1. , 1.5],
#       [2. , 2.5, 3. , 3.5]]) # Чтобы получить самую последнюю ось (в данном случае все столбцы), двоеточие писать необязательно. 
# Строки будут получены целиком по умолчанию:

In [ ]:
def get_chess(a):
    arr = np.zeros((a,a))
    print(arr)
    arr[1::2, ::2] = 1
    print(arr)
    arr[::2, 1::2] = 1
    return arr
    
get_chess(4)


# array([[0., 1., 0., 1.],
#        [1., 0., 1., 0.],
#        [0., 1., 0., 1.],
#        [1., 0., 1., 0.]])

In [ ]:
# СОРТИРОВКА ОДНОМЕРНЫХ МАССИВОВ
# Способ 1. Функция np.sort(<массив>) возвращает новый отсортированный массив:
arr = np.array([23,12,45,12,23,4,15,3])
arr_new = np.sort(arr)
print(arr)
# [23 12 45 12 23  4 15  3]
print(arr_new)
# [ 3  4 12 12 15 23 23 45]

# Способ 2. Функция <массив>.sort() сортирует исходный массив и возвращает None:
arr = np.array([23,12,45,12,23,4,15,3])
print(arr.sort())
# None
print(arr)
# [ 3  4 12 12 15 23 23 45]

In [ ]:
# РАБОТА С ПРОПУЩЕННЫМИ ДАННЫМИ
data = np.array([4, 9, -4, 3])
roots = np.sqrt(data)
roots
# RuntimeWarning: invalid value encountered in sqrt
# array([2.        , 3.        ,        nan, 1.73205081])
sum(roots)
# nan

# Для этого с помощью функции np.isnan(<массив>) узнаем, на каких местах в массиве находятся «не числа»:
np.isnan(roots)
# array([False, False,  True, False])
# Можно использовать полученный массив из True и False для извлечения элементов из массива roots, на месте которых в булевом массиве указано True.
# Таким способом можно узнать сами элементы, которые удовлетворяют условию np.isnan:
roots[np.isnan(roots)]
# array([nan])
# Этим элементам можно присвоить новые значения, например 0:
roots[np.isnan(roots)] = 0
roots
# array([2.        , 3.        , 0.        , 1.73205081]) # пропущенных элементов больше нет и можно считать сумму
sum(roots)
# 6.732050807568877

In [ ]:
# ВЕКТОРЫ В NUMPY И АРИФМЕТИКА
import numpy as np
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 + vec2 # сложение двух векторов
# array([14. , 10. , 10.6, 15.5])

[x + y for x, y in zip(list1, list2)] # списочное сокращение с применением функции zip()
# [14, 10, 10.6, 15.5]

vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 * vec2 # умножение векторов
# array([24. , 24. , 25.2, 32.5])

vec = np.arange(5)
vec * 10
# array([ 0, 10, 20, 30, 40])
vec ** 2
# array([ 0,  1,  4,  9, 16])

# векторы можно сравнивать друг с другом поэлементно
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 > vec2
# array([False, False,  True, False])

vec = np.array([14,15,9,26,53,5,89])
vec <= 26
# array([ True,  True,  True,  True, False,  True, False])

# Посчитаем длину следующего вектора:
vec = np.array([3, 4])
length = np.sqrt(np.sum(vec ** 2))
print(length)
# 5.0

length = np.linalg.norm(vec) # Для вычисления длины вектора нам потребуется функция norm, специальный подмодуль linalg
print(length)
# 5.0

# Реализуем вычисление расстояния в коде. Сначала — «сложным» способом напрямую из формулы:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.sqrt(np.sum((vec1 - vec2) ** 2))
distance
# 12.206555615733702

# А теперь применим более простой способ — используем уже известную нам функцию np.linalg.norm:
vec1 = np.array([0, 3, 5])
vec2 = np.array([12, 4, 7])
distance = np.linalg.norm(vec1 - vec2)
distance
# 12.206555615733702

# Реализуем это в коде (по-английски скалярное произведение называют dot — точечный — или scalar product, отсюда и такое название переменной):
vec1 = np.arange(1, 6)
vec2 = np.linspace(10, 20, 5)
scalar_product = np.sum(vec1 * vec2)
scalar_product
# 250.0

scalar_product = np.dot(vec1, vec2) # Для этого используют функцию np.dot(x, y):
scalar_product
# 250.0

In [ ]:
# БАЗОВЫЕ СТАТИСТИЧЕСКИЕ ФУНКЦИИ ДЛЯ ВЕКТОРОВ
vec = np.array([2,7,18,28,18,1,8,4])
vec.min()
# 1
np.max(vec)
# 28
vec.mean()
# 10.75

In [ ]:
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])
def min_max_dist(*vectors):
    len_tuple = len(vectors)
    array_dist = []
    i = 0
    for i in range(len_tuple):
        elem_dist = vectors[i]
        i += 1
        for elem in vectors:
            distance = np.linalg.norm(elem - elem_dist)
            if distance != 0: array_dist.append(distance)
    myarray = np.asarray(array_dist)
    return myarray.min(), myarray.max()
    

min_max_dist(vec1, vec2, vec3)

In [ ]:
vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3,4])
def any_normal(*vectors):
    len_tuple = len(vectors)
    i = 0
    while i in range(len_tuple):
        scalar_product = np.dot(vectors[i], vectors[i+1])
        vectors[i]
        vectors[i+1]
        i += 1
        if scalar_product == 0:
            return True
            break
            
print(any_normal(vec1, vec2, vec3))

In [ ]:
# СЛУЧАЙНЫЕ ЧИСЛА В NUMPY
import numpy as np
np.random.rand()
# 0.06600758835806675

np.random.rand(5)
# array([0.83745099, 0.58426808, 0.89206204, 0.41149807, 0.42445145])
np.random.rand(2, 3)

shape = (2, 3)
np.random.sample(shape) # Но в NumPy есть и другая функция, генерирующая массивы случайных чисел от 0 до 1,
# которая принимает в качестве аргумента именно кортеж без распаковки. Она называется sample:

# uniform(low=0.0, high=1.0, size=None)
np.random.uniform(0.5, 0.75, size=5)
np.random.uniform(-1000, 500, size=(2, 3))

np.random.randint(4, size=(2,3))
np.random.randint(6, 12, size=(3,3))

# Просто перемешать все числа в массиве позволяет функция random.shuffle.
# Функция random.shuffle перемешивает тот массив, к которому применяется, и возвращает None.
arr = np.arange(6)
print(arr)
# [0 1 2 3 4 5]
print(np.random.shuffle(arr))

# Чтобы получить новый перемешанный массив, а исходный оставить без изменений, можно использовать функцию random.permutation.
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(shuffled)
# ['The Beatles' 'Pink Floyd' 'Deep Purple' 'ACDC']
print(playlist)
# ['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']

np.random.permutation(10)
# array([7, 8, 2, 9, 4, 3, 1, 0, 5, 6])

# Чтобы получить случайный набор объектов из массива, используется функция random.choice:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate'] 
choice = np.random.choice(workers, size=2, replace=False)

choice = np.random.choice([1,2,3,4,5,6], size=10) # выборка с повторением
print(choice)
# [3 5 5 6 6 4 2 2 1 3]

# сгенерировать десять случайных чисел в диапазоне от 1 до 20 (включительно), которые гарантированно не будут повторяться
np.random.choice(np.arange(1, 21), size=10, replace=False)

np.random.seed(23) # SEED ГЕНЕРАТОРА ПСЕВДОСЛУЧАЙНЫХ ЧИСЕЛ
np.random.randint(10, size=(3,4))
# array([[3, 6, 8, 9],
#        [6, 8, 7, 9],
#        [3, 6, 1, 2]])

np.random.seed(100)
print(np.random.randint(10, size=3))
# [8 8 3]
print(np.random.randint(10, size=3))
# [7 7 0]
print(np.random.randint(10, size=3))
# [4 2 5]

In [ ]:
array = [1, 2, 3, 4, 5]
def shuffle_seed(array):
    seed_value = np.random.randint(0, 2**32, size=1, dtype=np.int64)
    shuffled = np.random.permutation(array)
    return shuffled, int(seed_value)
    
shuffle_seed(array)

In [ ]:
def get_loto(num):
    return(np.random.randint(1, 101, size=(num, 5, 5)))
    
get_loto(3)

In [ ]:
def get_unique_loto(num):
    arr = []
    i = 1
    while i <= num:
        arr_1 = np.random.choice(np.arange(1, 101), size=(5, 5), replace=False)
        arr.append(arr_1)
        i += 1
    
    myarray = np.asarray(arr)
    return myarray

get_unique_loto(10)
# print(np.shape(get_unique_loto(10)))